# Generated by Django 5.0.1 on 2024-02-26 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_post_title_alter_post_body_alter_post_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
